-- V1__init.sql
-- Initial schema for Oracle
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX users_username_uix ON users(username);
