-- V5__create_test_table.sql
-- Create a table to trigger the schema-level DDL trigger (test)

CREATE TABLE trigger_test (
  id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200)
);

-- Optionally add a comment so this DDL shows in the audit
COMMENT ON TABLE trigger_test IS 'Test table to validate schema-level DDL trigger';

