-- V6__create_ddl_audit_and_trigger_v.sql
-- New version of the schema-level DDL trigger using lowercase 'v' prefixes.
-- This is a new migration — V4 is left untouched.

-- Ensure audit table exists (no-op if already present)
BEGIN
  EXECUTE IMMEDIATE q'{
    CREATE TABLE ddl_audit (
      id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      event_time       TIMESTAMP DEFAULT SYSTIMESTAMP,
      ora_sysevent     VARCHAR2(100),
      db_username      VARCHAR2(128),
      os_user          VARCHAR2(128),
      client_ip        VARCHAR2(64),
      module_name      VARCHAR2(128),
      action_name      VARCHAR2(128),
      object_owner     VARCHAR2(128),
      object_name      VARCHAR2(128),
      object_type      VARCHAR2(128),
      ddl_text         CLOB
    )
  }';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN -- ignore "name is already used by an existing object"
      RAISE;
    END IF;
END;
/

-- New trigger (schema-level). Variables use lowercase 'v' prefixes.
CREATE OR REPLACE TRIGGER trg_ddl_audit_v
AFTER DDL ON SCHEMA
DECLARE
  v_line VARCHAR2(32767);
  v_clob CLOB;
  v_idx  PLS_INTEGER := 1;
  v_buf  VARCHAR2(32767);
BEGIN
  DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
  BEGIN
    LOOP
      -- ORA_SQL_TXT(index IN PLS_INTEGER, line OUT VARCHAR2)
      ORA_SQL_TXT(v_idx, v_line);
      EXIT WHEN v_line IS NULL;
      v_buf := v_line || CHR(10);
      DBMS_LOB.WRITEAPPEND(v_clob, LENGTH(v_buf), v_buf);
      v_idx := v_idx + 1;
    END LOOP;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
  END;

  INSERT INTO ddl_audit (
    ora_sysevent,
    db_username,
    os_user,
    client_ip,
    module_name,
    action_name,
    object_owner,
    object_name,
    object_type,
    ddl_text
  ) VALUES (
    ORA_SYSEVENT,
    SYS_CONTEXT('USERENV','SESSION_USER'),
    SYS_CONTEXT('USERENV','OS_USER'),
    SYS_CONTEXT('USERENV','IP_ADDRESS'),
    SYS_CONTEXT('USERENV','MODULE'),
    SYS_CONTEXT('USERENV','ACTION'),
    ORA_DICT_OBJ_OWNER,
    ORA_DICT_OBJ_NAME,
    ORA_DICT_OBJ_TYPE,
    v_clob
  );

  -- free temporary clob
  IF DBMS_LOB.ISTEMPORARY(v_clob) = 1 THEN
    DBMS_LOB.FREETEMPORARY(v_clob);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    -- swallow to avoid blocking DDL; consider external error logging
    BEGIN
      IF DBMS_LOB.ISTEMPORARY(v_clob) = 1 THEN
        DBMS_LOB.FREETEMPORARY(v_clob);
      END IF;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
END;
/
