-- V7__create_schema_ddl_trigger_no_sqltext.sql
-- Replace schema-level DDL trigger with a safe version that does NOT call ORA_SQL_TXT
-- Some Oracle versions expose ORA_SQL_TXT with different signatures; to avoid PLS-00306 errors
-- we store available DDL metadata but leave ddl_text NULL.

-- Ensure audit table exists (ignore if already present)
BEGIN
  EXECUTE IMMEDIATE q'{
    CREATE TABLE ddl_audit (
      id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      event_time       TIMESTAMP DEFAULT SYSTIMESTAMP,
      ora_sysevent     VARCHAR2(100),
      db_username      VARCHAR2(128),
      os_user          VARCHAR2(128),
      client_ip        VARCHAR2(64),
      module_name      VARCHAR2(128),
      action_name      VARCHAR2(128),
      object_owner     VARCHAR2(128),
      object_name      VARCHAR2(128),
      object_type      VARCHAR2(128),
      ddl_text         CLOB
    )
  }';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- Drop old triggers if present (ignore errors)
BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_ddl_audit';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_ddl_audit_v';
  EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

-- Create a safe schema-level DDL trigger that captures metadata but not full SQL text
CREATE OR REPLACE TRIGGER trg_ddl_audit_safe
AFTER DDL ON SCHEMA
BEGIN
  INSERT INTO ddl_audit (
    ora_sysevent,
    db_username,
    os_user,
    client_ip,
    module_name,
    action_name,
    object_owner,
    object_name,
    object_type,
    ddl_text
  ) VALUES (
    ORA_SYSEVENT,
    SYS_CONTEXT('USERENV','SESSION_USER'),
    SYS_CONTEXT('USERENV','OS_USER'),
    SYS_CONTEXT('USERENV','IP_ADDRESS'),
    SYS_CONTEXT('USERENV','MODULE'),
    SYS_CONTEXT('USERENV','ACTION'),
    ORA_DICT_OBJ_OWNER,
    ORA_DICT_OBJ_NAME,
    ORA_DICT_OBJ_TYPE,
    NULL
  );
EXCEPTION
  WHEN OTHERS THEN
    NULL; -- swallow to avoid blocking DDL
END;
/

