-- V8__create_additional_test_table.sql
-- Create another test table to exercise the schema-level DDL trigger

CREATE TABLE trigger_test_two (
  id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  description VARCHAR2(400),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE trigger_test_two IS 'Additional test table for DDL trigger validation';

